name: Node.js Package

on:
  push:
    release:
      types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: npmrcgen
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }}" > .npmrc
          echo "@managedkaos=https://npm.pkg.github.com/" >> .npmrc
          echo "email=michael@example.com" >> .npmrc
          echo "always-auth=true" >> .npmrc
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

        # publish-gpr:
        #   needs: build
        #   runs-on: ubuntu-latest
        #   permissions:
        #     packages: write
        #     contents: read
        #   steps:
        #     - uses: actions/checkout@v2
        #     - uses: actions/setup-node@v2
        #       with:
        #         node-version: 16
        #         registry-url: https://npm.pkg.github.com/
        #     - run: npm ci
        #     - run: npm publish
        #       env:
        #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
